### ISSUE TITLE
Not forwarding notifications

### ISSUE THREAD

**Issue by dissy614** [Elepover/notificationforwarder#1]
I've added a forward target of localhost, added chrome as an app to forward, disabled mute new apps, and enabled the forwarder.
The home screen shows 9 notifications received (while testing), but zero notifications forwarded and last successful forward date is "n/a"
It does show both the forwarder service on and listener status on, and 1/1 apps to forward.

I was attempting to capture the post data with a local web server ( http://localhost:8080/log ) and it does not show any connection attempts to the port.

Are there any additional URI requirements I am missing?  Is there anywhere the app might log?
I am using the compiled version from the windows store, v1.0.10.0

**Comment by Elepover** [comment]
Hello there, this might be due to UWP apps' local loopback network restriction.

You can try to type this command in any shell:

`checknetisolation loopbackexempt -d -n=32615Elepover.NotificationForwarder_ptway4kd3whcc`

For more information, check [this](https://stackoverflow.com/questions/33259763/uwp-enable-local-network-loopback) out.

If the problem wasn't resolved, feel free to add any follow-up info.

**Comment by Elepover** [comment]
Bonus: I'm planning to add a logs view to Notification Forwarder to assist troubleshooting. Will be released on about today.

On the current version, logs are only available through debugger (since I only used `Debug.WriteLine()` method)

**Comment by Elepover** [comment]
Just submitted a new version with logs available to the store, should be helpful for debugging.

Closing the issue. If you find anything that might potentially be a bug, feel free to reopen the issue.
